name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all --check

      - name: Test Default
        run: cargo test

      - name: Test Log Feature
        run: cargo test --features log

      - name: Check All Targets
        run: cargo check --all-targets --all-features

